language: node_js
node_js:
  - 12

cache:
  directories:
    - node_modules

jobs:
  include:
    - stage: test
      script: npm run test:ci -- --maxWorkers=2
    - stage: lint
      script: npm run lint
    - stage: build project
      script: npm build
