language: node_js
node_js:
  - 8.11.3

cache:
  yarn: true
  directories:
    - node_modules

jobs:
  include:
    - stage: test
      script: yarn test:ci --maxWorkers=2
    - stage: build project
      script: yarn build