environment:
  nodejs_version: ""

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install -g @angular/cli
  - npm install

test_script:
  - node -v
  - npm -v
  - npm run test:ci

build: off