version: 2
jobs:
  test:
    docker:
      - image: circleci/node:8.11.3
    parallelism: 4
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn test:ci --maxWorkers=2
  build:
    docker:
      - image: circleci/node:8.11.3
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: yarn build
  deploy:
    docker:
      - image: circleci/node:8.11.3
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: yarn build
      - run:
          name: Add Server to known_hosts
          command: ssh-keyscan -H $SSH_HOST >> ~/.ssh/known_hosts
      - add_ssh_keys:
          fingerprints:
          - "84:9e:f6:94:0c:6f:ff:10:95:9d:23:bd:9a:48:11:f5"
      - run:
          name: Deploy to ravens-scans.com
          command: |
            ssh $SSH_USER@$SSH_HOST; ./deploy_front.sh; echo "Done!";

workflows:
  version: 2
  test-build-and-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/