version: 2

defaults: &defaults
  working_directory: ~/reader-front
  docker:
    - image: circleci/node:12.13.1-browsers
  environment:
    TZ: '/usr/share/zoneinfo/America/Los_Angeles'

aliases:
  # Circle related commands
  - &restore-cache
    keys:
      # Find a cache corresponding to this specific package.json checksum
      # when this file is changed, this key will fail
      - reader-front-{{ checksum "package-lock.json" }}-{{ checksum ".circleci/config.yml" }}
      - reader-front-{{ checksum "package-lock.json" }}
      # Find the most recent cache used from any branch
      - reader-front-
  - &save-cache
      key: reader-front-{{ checksum "package-lock.json" }}-{{ checksum ".circleci/config.yml" }}
      paths:
        - $HOME/.npm
  # NPM commands
  - &install-dep
    name: Install Dependencies
    command: npm ci
  - &lint
    name: Lint
    command: npm run lint
  - &test
    name: Test
    command: npm run test:ci -- --maxWorkers=2
  - &build-app
    name: Building app
    command: npm build
  - &deploy
    name: Deploy
    command: curl $SECRET_HOST_RS?id=$SECRET_TOKEN_RS

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *restore-cache
      - run: date
      - run: *install-dep
      - save_cache: *save-cache
      - persist_to_workspace:
          root: .
          paths:
            - .
  lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/reader-front
      - run: *lint
  test:
    <<: *defaults
    parallelism: 4
    steps:
      - attach_workspace:
          at: ~/reader-front
      - run: *test
      - run:
          name: Send CodeCov Results
          command: bash <(curl -s https://codecov.io/bash) -t $CODECOV_KEY
  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/reader-front
      - run: *build-app
      - persist_to_workspace:
          root: .
          paths:
            - .
  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/reader-front
      - run: *deploy
      

workflows:
  version: 2
  build_and_test:
    jobs:
      - install:
          filters:
            tags:
              only: /.*/

      - lint:
          requires:

            - install
          filters:
            tags:
              only: /.*/

      - test:
          requires:
            - install
          filters:
            tags:
              only: /.*/

      - build:
          requires:
            - install
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - install
            - lint
            - test
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
