name: Shared pipeline

on:
  push:
    paths:
      - "packages/shared/**"

env:
  CI: true

jobs:
  run:
    name: Node 14
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - run: node --version
      - run: yarn --version

      - name: Install npm dependencies
        run: yarn install

      - name: Run build
        run: yarn build:shared

      - name: Run tests
        run: yarn test:shared -- --maxWorkers=2
