name: API pipeline

on: [push, pull_request]

env:
  CI: true
  SECRET_KEY: super-secret-key-readerfront-api
  GRAPHQL_IDE: true

  DB_USER: USER
  DB_PASS: PASS
  DB_NAME: DBNAME
  DB_HOSTNAME: 127.0.0.1
  DB_DIALECT: mysql
  APP_URL: http://localhost:3000/
  API_URL: http://localhost:8000/
  REACT_APP_APP_TITLE: Reader Front
  SENDGRID_API: YOUR_API_KEY
  EMAIL: YOUR_EMAIL

jobs:
  run:
    name: Node 14
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"

      - run: node --version
      - run: yarn --version

      - name: Install npm dependencies
        run: yarn install

      - name: Run lint
        run: yarn lint:admin

      - name: Run build
        run: yarn build:admin

      - name: Run tests
        run: yarn test:admin -- --maxWorkers=2
