name: Shared pipeline

on:
  push:
    paths:
      - "packages/shared/**"

env:
  CI: true

jobs:
  run:
    name: Node 14
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"

      - run: node --version
      - run: yarn --version

      - name: Install npm dependencies
        run: yarn install

      - name: Run build
        run: yarn build:shared

      - name: Run tests
        run: yarn test:shared -- --maxWorkers=2
