name: UI pipeline

on:
  push:
    paths:
      - "packages/ui/**"
      - "packages/shared/**"

env:
  CI: true

jobs:
  run:
    name: Node 14
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"

      - uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - run: node --version
      - run: yarn --version

      - name: Install npm dependencies
        run: yarn install

      - run: yarn build:shared

      - name: Run build
        run: yarn build:ui

      # - name: Run tests
      #   run: yarn test:ui -- --maxWorkers=2
