name: Admin pipeline

on:
  push:
    paths:
      - "packages/admin/**"
      - "packages/shared/**"
      - "packages/ui/**"

env:
  CI: true
  REACT_APP_APP_URL: http://localhost:3000/
  REACT_APP_READER_PATH: http://localhost:8000/
  REACT_APP_APP_PATH: /
  REACT_APP_APP_TITLE: Reader Front
  REACT_APP_GA_ID: UA-XXXXXXXXX-X
  REACT_APP_CDNS: photon
  REACT_APP_LANGUAGES: en,es

jobs:
  run:
    name: Node 14
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"

      - uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - run: node --version
      - run: yarn --version

      - name: Install npm dependencies
        run: yarn install

      - run: yarn build:shared
      - run: yarn build:ui

      - name: Run lint
        run: yarn lint:admin

      - name: Run build
        run: yarn build:admin

      - name: Run tests
        run: yarn test:admin -- --maxWorkers=2
