name: Tests

on: [push, pull_request]

env:
  CI: true
  REACT_APP_APP_URL: http://localhost:3000/
  REACT_APP_READER_PATH: http://localhost:8000/
  REACT_APP_APP_PATH: /
  REACT_APP_APP_TITLE: Reader Front
  REACT_APP_GA_ID: UA-XXXXXXXXX-X
  REACT_APP_CDNS: photon
  REACT_APP_LANGUAGES: en,es

jobs:
  run:
    name: Node ${{ matrix.node }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node: [12, 13]

    steps:
      - name: Clone repository
        uses: actions/checkout@v1
        with:
          fetch-depth: 3
      - name: Set Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - run: node --version
      - run: npm --version

      - name: Install npm dependencies
        run: npm --prefix ./admin ci

      - name: Run lint
        run: npm --prefix ./admin run lint

      - name: Run build
        run: npm --prefix ./admin build

      - name: Run tests
        run: npm --prefix ./admin test -- --maxWorkers=2

      - name: Run Coveralls
        uses: coverallsapp/github-action@master
        if: matrix.node == 10
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'
          path-to-lcov: './js/coverage/lcov.info'
